[versions]
kotlin = "2.2.20"
serialization = "1.9.0"
coroutines = "1.8.0"

[libraries]
serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "2.0.0" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.8" }
licensee = { id = "app.cash.licensee", version = "1.14.0" }
mavencentral = { id = "io.github.hfhbd.mavencentral", version = "0.0.23" }
